#!/bin/sh

. /opt/app/lib/app-constants.sh

LOGS=/var/log/${APP_NAME}

case "$1" in
  start)
    echo "Starting ${APP_NAME}"
    nohup java -jar "${APP_LOCATION}/${APP_NAME}.jar" &
    PID=$!
    echo "Started ${APP_NAME} with PID: ${PID} in ${PID_FILE}"
    sudo touch ${PID_FILE}
    sudo echo -e "${PID}" | sudo tee ${PID_FILE}
    ;;
  stop)
    echo "Stopping ${APP_NAME}"
    if [ -f $PID_FILE ]; then
      PID=`cat ${PID_FILE}`
      echo "Stopping ${APP_NAME} running with ${PID}"
      test -z $PID || kill $PID
      sudo rm $PID_FILE
    else
      echo "Already stopped"
    fi
    ;;
esac
